# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master
#- dev

pool:
    vmImage: 'vs2017-win2016'

variables:
  Configuration: Release

steps:
- pwsh: ./build.ps1 -NoBuild -Bootstrap
  displayName: 'Running ./build.ps1 -NoBuild -Bootstrap'

- pwsh: |
      $ErrorActionPreference = "Stop"
      ./build.ps1 -Clean -Configuration Release
  displayName: './build.ps1 -Clean -Configuration Release'

#- pwsh: ./test/E2E/Start-E2ETest.ps1
#  env:
#    AzureWebJobsStorage: $(AzureWebJobsStorage)
#    AzureWebJobsCosmosDBConnectionString: $(AzureWebJobsCosmosDBConnectionString)
#    AzureWebJobsServiceBus: $(AzureWebJobsServiceBus)
#    AzureWebJobsEventHubSender: $(AzureWebJobsEventHubSender)
#    FUNCTIONS_WORKER_RUNTIME : "powershell"
#  continueOnError: false
#  displayName: 'Running E2ETest'

- pwsh: |
      <#
      write-host "Current path"
      ls
      write-host "Package folder "
      ls ./package/bin
      $sourcePath  = (ls ./package/bin/**/*/Microsoft.Azure.Functions.PowerShellWorker*.nupkg).FullName
      if (-not test-path $sourcePath)
      {
        throw 'Unable to find Microsoft.Azure.Functions.PowerShellWorker*.nupkg at ./package'
      }
      #>
      Copy-Item -Path $sourcePath -Destination $(Build.ArtifactStagingDirectory) -ErrorAction Stop -Verbose -Force
  displayName: 'Copy package to ArtifactStagingDirectory' 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '38971840-434a-4bcc-87cf-218cc186092e'